# Generated by Django 5.0.6 on 2024-06-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #if any changes will be made and the new file will contain the dependencies of the previous files
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                #The 'id' field is added automatically it basically acts as a primary key.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TimeField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
